### ISSUE TITLE
拖动代码处理的不是太好，窗体加载后是整个都可以拖动的，应该是头部可拖动才对。

### ISSUE THREAD

**Issue by jackletter** [qwqcode/Nacollector#5]
自己调试的时候已经处理这个问题：
1.  DragDropHandler.cs
public class DragDropHandler : IDragHandler
    {
        public Region draggableRegion = null;//默认改为null、
        。。。。。。。

2.  DragDropHandler
 public void OnDraggableRegionsChanged(IWebBrowser browserControl, IBrowser browser, IList<DraggableRegion> regions)
        {
            //if (!Enable)
            //{
            //    return;
            //}

**Comment by qwqcode** [comment]
> 自己调试的时候已经处理这个问题：
> 
>     1. DragDropHandler.cs
>        public class DragDropHandler : IDragHandler
>        {
>        public Region draggableRegion = null;//默认改为null、
>        。。。。。。。
> 
>     2. DragDropHandler
>        public void OnDraggableRegionsChanged(IWebBrowser browserControl, IBrowser browser, IList regions)
>        {
>        //if (!Enable)
>        //{
>        //    return;
>        //}

DragDropHandler.cs 确实有问题，每次调用 OnDraggableRegionsChanged 方法都会执行`draggableRegion = null;` 从而导致 `draggableRegion.Union(...)` 失效

设置 `Enable` 这个 public 成员变量的意图是控制拖动功能的开启与关闭 [/Nacollector/Browser/CrBrowser.cs#L48](https://github.com/qwqcode/Nacollector/blob/45467f014ec1ed9dc4e2adf17b5207260e0768eb/Nacollector/Browser/CrBrowser.cs#L48) 所以判断 `Enable` 是有用的

非常感谢您的反馈 😀

**Comment by qwqcode** [comment]
> 自己调试的时候已经处理这个问题：
> 
> 1. DragDropHandler.cs
>    public class DragDropHandler : IDragHandler
>    {
>    public Region draggableRegion = null;//默认改为null、
>    。。。。。。。
> 2. DragDropHandler
>    public void OnDraggableRegionsChanged(IWebBrowser browserControl, IBrowser browser, IList regions)
>    {
>    //if (!Enable)
>    //{
>    //    return;
>    //}

原先的 DragDropHandler.cs 确实有些地方有问题，已修改（draggableRegion 默认值改为 null，Enable 默认值改为 false）

 #6

在网页加载前，Nacollector 会判断 URL，仅本地 URL 启用 窗口拖动功能（因为 CefSharp 还会被用来加载其他网页，所以  Nacollector 对于拖动的这个功能默认关闭）

https://github.com/qwqcode/Nacollector/blob/45467f014ec1ed9dc4e2adf17b5207260e0768eb/Nacollector/Browser/CrBrowser.cs#L61

OnDraggableRegionsChanged 方法里判断 Enable 值的作用就是控制  开启和关闭
